### ISSUE TITLE
tskit metadata

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#288]
When tree sequences are sufficiently large, we cannot output to tskit.

For example:

```
Start sim: 2019-08-22 19:38:01.164465
End sim: 2019-08-22 19:44:11.201700
[50000000 50000000 50000000 ...        0        0        0]
Start binary dump: 2019-08-22 19:44:11.203341
End binary dump: 2019-08-22 19:44:27.138745
Start dump to tskit: 2019-08-22 19:44:27.138781
Traceback (most recent call last):
  File "simulate.py", line 80, in <module>
    ts = pop.dump_tables_to_tskit()
  File "/home/molpopgen/src/fwdpy11/fwdpy11/_tables_to_tskit.py", line 114, in dump_tables_to_tskit
    node_to_individual = _initializeIndividualTable(pop, tc)
  File "/home/molpopgen/src/fwdpy11/fwdpy11/_tables_to_tskit.py", line 90, in _initializeIndividualTable
    tc.individuals.set_columns(flags=flags, metadata=md, metadata_offset=mdo)
  File "/usr/local/lib/python3.7/dist-packages/tskit/tables.py", line 293, in set_columns
    metadata=metadata, metadata_offset=metadata_offset))
_tskit.LibraryError: Table column too large; cannot be more than 2**31 bytes.
```

The 32 bit signed integers used in `tskit` are simply too small.  This is unfortunate, as the limit is 2Gb, which isn't too large.

Possible workarounds:

1. Detect at run time when this happens and dispatch to an alternate strategy where the metadata become integers into a numpy record array of metadata that is returned separately and has to be dealt with.
2. Replace our current scheme with one using less space (`struct`, for example).  This really only kicks the can down the road.

**Comment by molpopgen** [comment]
When tskit 0.3.0 is out, we will refactor and use their struct codec to reduce memory use.  We'll also explore the JSON codec for some tables to see if eliminating optional metadata fields yields smaller files.

**Comment by molpopgen** [comment]
This issue will "take care of itself" once tskit uses 64-bit offsets for these columns.

**Comment by molpopgen** [comment]
Close this when 0.17.0 is the stable release.
