### ISSUE TITLE
Add plug-in building to GtHub workflow.

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#618]
There may be an issue with plug in building on conda.  The actions use conda but don't try to bud the example. They do, however, build a lot of C++ stuff for the test suite.  In any case, let's add this and see.

Cc @apragsdale

**Comment by molpopgen** [comment]
The specific issue at hand gives this error:

```
 Traceback (most recent call last):
   File "bgs.py", line 72, in <module>
     pop, r = runsim(seed)
   File "bgs.py", line 57, in runsim
     fwdpy11.evolvets(
   File "/home/aaronragsdale/anaconda3/envs/BGS/lib/python3.8/site-packages/fwdpy11/_evolvets.py", line 165, in evolvets
     evolve_with_tree_sequences(
 TypeError: __call__(): incompatible function arguments. The following argument types are supported:
     1. (self: freqtracker.FreqTracker, arg0: fwdpy11::DiploidPopulation, arg1: fwdpy11::SampleRecorder) -> None
 
 Invoked with: <freqtracker.FreqTracker object at 0x7f150551ad70>, <fwdpy11._fwdpy11.DiploidPopulation object at 0x7f15054fe2f0>, <fwdpy11._fwdpy11.SampleRecorder object at 0x7f150551ae70>
```

**Comment by molpopgen** [comment]
While on this, let's make sure docs say that conda compilers are required if trying to compile plugins in that environment.

**Comment by molpopgen** [comment]
The error that @apragsdale experienced appears to be due to mixing system + conda compilers.  This definitely needs to get into the docs (see #619).
