### ISSUE TITLE
Need better documentation about exporting Python parameters to tskit provenance.

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#724]
This type doesn't recurse through its members, which is probably the cause of errors like this:

```
Traceback (most recent call last):
  File "simulate/prototype.py", line 67, in <module>
    tskit_ts = pop.dump_tables_to_tskit(
  File "/home/kevin/src/fwdpy11/fwdpy11/_types/diploid_population.py", line 218, in dump_tables_to_tskit
    return fwdpy11.tskit_tools._dump_tables_to_tskit._dump_tables_to_tskit(
  File "/home/kevin/src/fwdpy11/fwdpy11/tskit_tools/_dump_tables_to_tskit.py", line 211, in _dump_tables_to_tskit
    tc.provenances.add_row(json.dumps(provenance))
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type GaussianS is not JSON serializable
```

**Comment by molpopgen** [comment]
The example above was due to not casting the dict to str.  Basically, this is a docs fail.

**Comment by molpopgen** [comment]
We can probably also improve the API to use `try/except` to distinguish "already `str`" from `object`.
