### ISSUE TITLE
Error in branch/split models imported from demes.

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#881]
A reminder issue for when I get back to work after the holiday break:

Getting this from the `dev` branch when running the demographic model part of the [test suite](https://github.com/molpopgen/fwdpy11_statistical_tests/):

```
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "python/plot_model_residuals.py", line 114, in runsim
    fwdpy11.evolvets(rng, pop, params, 100)
  File "/usr/local/lib/python3.8/dist-packages/fwdpy11/_evolvets.py", line 166, in evolvets
    evolve_with_tree_sequences(
fwdpy11._fwdpy11.DemographyError: non-zero migration rate from empty parental deme 1 into destination deme 0
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "python/plot_model_residuals.py", line 220, in <module>
    sim_fs = f.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
fwdpy11._fwdpy11.DemographyError: non-zero migration rate from empty parental deme 1 into destination deme 0
[Sat Dec 25 00:22:47 2021]
Error in rule generate_residuals_plot:
    jobid: 2
    output: recent_admixture_asymmetric_migration_in_ancestor.png
    shell:
        python3 python/plot_model_residuals.py --yaml yaml/recent_admixture_asymmetric_migration_in_ancestor.yml --nreps 512 --nthreads 8
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /app/.snakemake/log/2021-12-24T234226.258491.snakemake.log
```

Oddly, modifying the runner to use the `fwdpy11.DemographyDebugger` does  not raise errors.

Things to do:

- Are we testing a model like this in the test suite? If not, add such a test.
- Any chance this is related to changes from #822, which made it into 0.16.0?
- Any chance that the yaml files in the test suite need updating due to demes 0.2.0?

Definitely seems like I want to run the test suite more often!

cc @apragsdale

**Comment by molpopgen** [comment]
This is the model.

![foo](https://user-images.githubusercontent.com/6416159/147375445-0241fe10-f91b-4828-9aaa-2da6e4f30b28.png)

**Comment by molpopgen** [comment]
And the low-level objects:

```py
fwdpy11.DiscreteDemography(
    mass_migrations=[],
    set_growth_rates=[],
    set_deme_sizes=[
        fwdpy11.SetDemeSize(when=1000, deme=1, new_size=760, resets_growth_rate=True),
        fwdpy11.SetDemeSize(when=2000, deme=0, new_size=0, resets_growth_rate=True),
        fwdpy11.SetDemeSize(when=2000, deme=1, new_size=0, resets_growth_rate=True),
        fwdpy11.SetDemeSize(when=2000, deme=2, new_size=500, resets_growth_rate=True),
    ],
    set_selfing_rates=[
        fwdpy11.SetSelfingRate(when=0, deme=0, S=0),
        fwdpy11.SetSelfingRate(when=1000, deme=1, S=0),
        fwdpy11.SetSelfingRate(when=2000, deme=2, S=0),
    ],
    migmatrix=fwdpy11.MigrationMatrix(
        migmatrix=array([[1.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]),
        scaled=False,
    ),
    set_migration_rates=[
        fwdpy11.SetMigrationRates(
            when=1000, deme=0, migrates=array([9.99995e-01, 5.00000e-06, 0.00000e00])
        ),
        fwdpy11.SetMigrationRates(when=1000, deme=1, migrates=array([1.0, 0.0, 0.0])),
        fwdpy11.SetMigrationRates(
            when=1001, deme=1, migrates=array([1.000e-04, 9.999e-01, 0.000e00])
        ),
        fwdpy11.SetMigrationRates(when=2000, deme=0, migrates=array([0.0, 0.0, 0.0])),
        fwdpy11.SetMigrationRates(when=2000, deme=1, migrates=array([0.0, 0.0, 0.0])),
        fwdpy11.SetMigrationRates(when=2000, deme=2, migrates=array([0.8, 0.2, 0.0])),
        fwdpy11.SetMigrationRates(when=2001, deme=2, migrates=array([0.0, 0.0, 1.0])),
    ],
)
```

**Comment by molpopgen** [comment]
Other problem: the Python demography debugger *does not catch* this model as an error.  So is the debugger wrong, or the runtime checking during the sim wrong?

**Comment by molpopgen** [comment]
This error seems to be related to a more general problem re: asymmetric migration rates. Invalid imports of such models are passing the debugger (#887).  We do not have great coverage of asymmetric migration models (#818).  Finally, relying on the buggy debugger and skipping a trip through `fwdpy11.evolvets` means that we failed to catch this earlier.

**Comment by molpopgen** [comment]
This seems to be an error specific to setting up migration rates in "branch" scenarios, which means that a daughter deme splits off and the ancestral deme remains.  (A branch contrasts from a split, in which A "buds off" into B and C.)  One clue to fixing this may be that splits pass all tests.

**Comment by molpopgen** [comment]
Notes for later:. Need to figure out what distinguishes the branches from "branch split" tests.
